spring.application.name=pizzariadomario

# SQL Server Configuration
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=pizzariamariodb;integratedSecurity=false;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=@ITB123456
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# JPA Configuration
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect

# JWT (JSON Web Token)
application.security.jwt.secret-key= MyScret
application.security.jwt.expiration=86400000
application.security.jwt.refresh-token.expiration=604800000

# obs: 86400000   1 dia (milissegundos)
#      604800000  7 dias (milissegundos)


# Informações

# integratedSecurity: (true) Indica que a conexão será feita com as credenciais do Windows (false) Credencial do SQL Server
# encrypt: (true) Requer criptografia do cliente (false) não requer criptografia do cliente
# trustServerCertificate: (true) Instrui o aplicativo cliente a ignorar a validação do certificado SSL/TSL do servidor

# spring.jpa.hibernate.ddl-auto
     # none :   Banco de dados e tabelas devem ser criados com antecedência
     # update : Banco de dados deve ser criado com antecedência, tabelas podem ser criadas com antecedência, as tabelas são atualizadas pelo código (model )
     # create-drop : Banco de dados deve ser criado com antecedência, as tabelas são criadas automaticamente pelo código (model), entretanto as tabelas
     #               serão excluídas toda vez que o servidor é "desligado"
     # create:  Banco de dados deve ser criado com antecedência, quando o servidor carrega as tabelas são recriadas, as tabelas não serão excluídas
     #           quando o servidor é "desligado"





